[package]
name = "termsize-alt"
version = "0.2.0"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Retrieves terminal size"
repository = "https://github.com/zhongdongy/termsize-alt"
homepage = "https://github.com/softprops/termsize"
documentation = "http://softprops.github.io/termsize"
keywords = ["tty", "terminal", "term", "size", "dimensions"]
license = "MIT"
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "softprops/termsize" }
coveralls = { repository = "softprops/termsize" }

[target.'cfg(unix)'.dependencies]
atty = "0.2"
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["handleapi"] }
